"""Captain's Card: one character challenge a day.

Each one is something a 10-year-old can actually do today, at school or at
home. "how" is the concrete play. "why" is the reason, in plain words.

These are advice, not facts, so they carry no sources. The rule that keeps
them honest is: no made-up statistics and no "studies show". Just the reason.

[name, goal, how, why]
"""

CHALLENGES = [
    ["Attentive", "Be attentive today.",
     "When a teacher or parent is talking to you, stop what you're doing, look at them, and don't talk until they're done.",
     "Listening the first time means you don't miss the play call, in class or on the field."],
    ["Respectful", "Be respectful today.",
     "Use please and thank you, and keep a kind voice, even when you're frustrated.",
     "People remember how you treat them, especially when things aren't going your way."],
    ["Responsible", "Be responsible today.",
     "Do your jobs without being reminded. Check your list before you leave the house.",
     "Captains don't wait to be told. They get it done."],
    ["Kind", "Be kind today.",
     "Do one kind thing for someone who doesn't expect it.",
     "One small kind thing can turn someone's whole day around."],
    ["Brave", "Be brave today.",
     "Try something new, even if you might not be good at it yet.",
     "Every great player was bad at their move the first time they tried it."],
    ["Patient", "Be patient today.",
     "When you have to wait, take a slow breath instead of complaining.",
     "Waiting well is a skill, just like a good first touch."],
    ["Honest", "Be honest today.",
     "Tell the truth, even when it's hard. If you mess up, say so.",
     "When people know you tell the truth, they trust you with more."],
    ["Helpful", "Be helpful today.",
     "Help out at home once without being asked.",
     "A team works when everybody pitches in, and a family is a team."],
    ["Coachable", "Be coachable today.",
     "When a teacher or coach corrects you, say \"Got it\" and try it their way.",
     "The players who get better fastest are the ones who listen to coaching."],
    ["Grateful", "Be grateful today.",
     "Say thank you to three people, and say what you're thanking them for.",
     "Noticing the good stuff makes the whole day feel better."],
    ["Organized", "Be organized today.",
     "Put your things back where they belong, and pack your bag before bed.",
     "No more searching for your cleats five minutes before you leave."],
    ["A good sport", "Be a good sport today.",
     "Win or lose, in a game or a video game, say \"good game\" and mean it.",
     "How you act when you lose says a lot about who you are."],
    ["Persistent", "Don't give up today.",
     "When something is hard, take a breath and try again before asking for help.",
     "Hard things get easier when you keep showing up."],
    ["A leader", "Be a leader today.",
     "Include someone who's left out, at lunch, at recess or in a game.",
     "Leaders make sure everyone is part of the team."],
    ["Focused", "Be focused today.",
     "When it's work time, do one thing at a time until it's done.",
     "Focus is like a muscle. Use it and it gets stronger."],
    ["Positive", "Stay positive today.",
     "When something goes wrong, say \"next play\" and keep going.",
     "You can't change the last play. You can win the next one."],
    ["Encouraging", "Be encouraging today.",
     "Cheer on a classmate or teammate when they try something hard.",
     "Everyone plays better when someone believes in them."],
    ["Calm", "Keep your cool today.",
     "When you get upset, take three slow breaths before you say anything.",
     "Your best decisions come when you're calm, not when you're mad."],
    ["Prepared", "Be prepared today.",
     "Get your homework and gear ready the night before.",
     "Ready players play better, and ready students do too."],
    ["On time", "Be on time today.",
     "Be ready to go when it's time to leave, with your shoes on.",
     "Being on time shows people you care about their time too."],
    ["Tidy", "Be tidy today.",
     "Leave your room, or one other room, cleaner than you found it.",
     "Taking care of your space is taking care of your team at home."],
    ["A good listener", "Be a good listener today.",
     "Let other people finish talking before you speak.",
     "You learn more when you're listening than when you're talking."],
    ["A hard worker", "Work hard today.",
     "Give your best effort on something you don't love doing.",
     "Anyone works hard at the fun stuff. Champions work hard at the boring stuff too."],
    ["Polite", "Be polite today.",
     "Look people in the eye when you say hi, thank you and goodbye.",
     "Good manners are a way of showing respect."],
    ["Generous", "Be generous today.",
     "Share something, like a snack, a turn, or the ball.",
     "Sharing makes you the kind of teammate people want."],
    ["Self-controlled", "Show self-control today.",
     "When you want to blurt something out, raise your hand or wait your turn.",
     "Controlling yourself is the first step to controlling the game."],
    ["Forgiving", "Be forgiving today.",
     "If someone makes a mistake or bumps into you, let it go.",
     "Everybody messes up. Holding a grudge just weighs you down."],
    ["Curious", "Be curious today.",
     "Ask one good question in class.",
     "Asking questions is how smart people get smarter."],
    ["A team player", "Be a team player today.",
     "Share the credit. When something goes well, thank the people who helped.",
     "Nobody wins a game by themselves."],
    ["Trustworthy", "Be trustworthy today.",
     "Do what you said you'd do, even the small stuff.",
     "When your word is good, people count on you."],
    ["Gentle", "Be gentle today.",
     "Be extra patient and kind with someone younger than you.",
     "Younger kids watch what older kids do. Show them how it's done."],
    ["Hardworking at school", "Own your schoolwork today.",
     "Start your homework without being reminded, and check it before you call it done.",
     "Doing it right the first time saves time for the fun stuff."],
]

# Quick-add ideas for his assignments, so he doesn't have to type them every day.
JOB_IDEAS = ["Homework", "Pack my bag", "Make my bed", "Feed the pet", "Practice", "Clean my room",
             "Put away laundry", "Set the table", "Read for 20 min", "Help with dishes"]
