"""Liam's quotes: sports legends, with a kid-level "What does this mean?".

Only lines that are reliably attributed to the person named. Some famous
"sports quotes" were really said by someone else (a coach describing a player,
or a later paraphrase with no real source). Those are out.

Each entry: (quote, who, tags, meaning, question to think about)
tags use the same keys as the trivia: soccer, football, basketball, baseball, more
"""

QUOTES = [
("Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing.",
 "Pelé", ["soccer"],
 "Pelé is saying the best players didn't get lucky. They practiced, kept going when it was hard, and kept learning. The last part matters most: he says loving the game is what keeps you doing all the rest.",
 "What do you love doing so much that practicing it doesn't feel like work?"),
("The more difficult the victory, the greater the happiness in winning.",
 "Pelé", ["soccer"],
 "An easy win feels fine. A win you had to fight for, when you were losing or tired, feels amazing. So a hard game isn't bad news. It's the chance for the best kind of win.",
 "What's something hard you did that felt great when you finished it?"),
("Everything is practice.",
 "Pelé", ["soccer"],
 "Three words, and a big idea. Every game, every kickabout in the yard, every time you try something new, you're getting better. Nothing is wasted.",
 "What could you practice today without anyone telling you to?"),
("You have to fight to reach your dream. You have to sacrifice and work hard for it.",
 "Lionel Messi", ["soccer"],
 "Messi was small as a kid and needed medicine to help him grow. He moved to another country at 13 to chase soccer. Dreams don't just happen, he says. You work for them, and sometimes you give things up.",
 "What's your dream, and what's one small thing you can do for it this week?"),
("Talent without working hard is nothing.",
 "Cristiano Ronaldo", ["soccer"],
 "Lots of kids are talented. Ronaldo is famous for training harder than almost anyone, even when he was already a star. Talent is where you start. Work is what gets you somewhere.",
 "What are you naturally good at that you could get even better at?"),
("Playing football is very simple, but playing simple football is the hardest thing there is.",
 "Johan Cruyff", ["soccer"],
 "Cruyff was one of the smartest players ever. He means the best players don't show off. They make the easy pass at the right time. Keeping it simple sounds easy but takes real skill.",
 "When do you try to do too much, when something simple would work better?"),
("Every disadvantage has its advantage.",
 "Johan Cruyff", ["soccer"],
 "If you're small, you might be quicker. If you're new, you see things others miss. Cruyff says every weakness hides a strength if you look for it.",
 "What's something you think is a weakness that might secretly help you?"),
("I am a member of a team, and I rely on the team, I defer to it and sacrifice for it, because the team, not the individual, is the ultimate champion.",
 "Mia Hamm", ["soccer"],
 "Mia Hamm was one of the best players in the world, and she still said the team matters more than any one player. \"Defer\" means you let the team's needs come first.",
 "How can you help your team today, even when you're not the one scoring?"),
("Always work hard, never give up, and fight until the end because it's never really over until the whistle blows.",
 "Alex Morgan", ["soccer"],
 "Games have been won in the very last minute. If you give up early, you'll never know if you could have come back. Keep going until the ref says it's over.",
 "When did something turn around right at the end?"),
("Make failure your fuel.",
 "Abby Wambach", ["soccer"],
 "Fuel is what makes a car go. Wambach is saying that losing, or messing up, can push you to work harder next time, instead of making you quit.",
 "What's a time you messed up, that made you want to get better?"),
("Hard work will always overcome natural talent when natural talent does not work hard.",
 "Sir Alex Ferguson", ["soccer"],
 "Ferguson coached Manchester United for 26 years. He saw lots of gifted players who didn't try hard, and lots of hard workers who beat them. If you work hard, you can beat people who are more talented than you.",
 "What's something you got better at just by sticking with it?"),
("I've missed more than 9,000 shots in my career. I've lost almost 300 games. 26 times I've been trusted to take the game-winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed.",
 "Michael Jordan", ["basketball"],
 "The greatest basketball player ever missed a lot. He kept taking the shot anyway. You can't make the big shot if you're too scared of missing it.",
 "What would you try if you weren't worried about missing?"),
("Talent wins games, but teamwork and intelligence win championships.",
 "Michael Jordan", ["basketball"],
 "One great player can win you a game. To win a whole season, you need everyone playing together and thinking smart. Even Jordan needed his team.",
 "What makes a team play well together?"),
("You miss 100% of the shots you don't take.",
 "Wayne Gretzky", ["more"],
 "If you never shoot, you can never score. It's simple math. Gretzky, the greatest hockey scorer ever, is saying: take your chances.",
 "What's one \"shot\" you could take today, in class or at practice?"),
("It's hard to beat a person who never gives up.",
 "Babe Ruth", ["baseball"],
 "You can beat someone who's faster or stronger. But someone who keeps coming back, over and over, is really tough to beat. Not giving up is like a superpower.",
 "Who do you know who never gives up?"),
("A life is not important except in the impact it has on other lives.",
 "Jackie Robinson", ["baseball"],
 "Jackie Robinson was the first Black player in modern Major League Baseball. He's saying what matters most isn't trophies. It's how you help and change other people's lives.",
 "How could you make someone's day better today?"),
("I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'",
 "Muhammad Ali", ["more"],
 "Even the greatest boxer didn't love training. He did it anyway, because he knew the hard part now would be worth it later. It's okay to not love practice. Just keep doing it.",
 "What's something you don't love doing, that's worth doing anyway?"),
("Float like a butterfly, sting like a bee.",
 "Muhammad Ali", ["more"],
 "Ali was a heavyweight who moved as lightly as a much smaller fighter. Quick on his feet, and then, pow! It's a fun way of saying: be light and quick, then strike hard.",
 "What sport or game would \"float like a butterfly\" help you in?"),
("I really think a champion is defined not by their wins but by how they can recover when they fall.",
 "Serena Williams", ["more"],
 "Everyone loses sometimes, even Serena. What makes a real champion is getting back up after a loss and trying again.",
 "How do you bounce back after a bad game or a bad day?"),
("I'm not the next Usain Bolt or Michael Phelps. I'm the first Simone Biles.",
 "Simone Biles", ["more"],
 "People kept comparing her to other stars. She said no: she's her own person. You don't have to be the next somebody. You can be the first you.",
 "What makes you different from everyone else?"),
("We all have dreams. But in order to make dreams come into reality, it takes an awful lot of determination, dedication, self-discipline, and effort.",
 "Jesse Owens", ["more"],
 "Jesse Owens won four gold medals in 1936. He's listing what it takes to turn a dream into something real. Dreaming is the easy part. The work is the hard part.",
 "Which of those four words do you need most right now?"),
("Don't let what you cannot do interfere with what you can do.",
 "John Wooden", ["basketball"],
 "Wooden was a legendary basketball coach. If you can't shoot threes yet, you can still pass, defend and hustle. Focus on what you can do.",
 "What's one thing you're already good at that you can use today?"),
("Be quick, but don't hurry.",
 "John Wooden", ["basketball"],
 "Being quick means moving fast and in control. Hurrying means rushing and making mistakes. The best players are fast, but they stay calm.",
 "When do you rush and make silly mistakes?"),
("Things turn out best for the people who make the best of the way things turn out.",
 "John Wooden", ["basketball"],
 "Things won't always go your way. You might not start, or it might rain on game day. The people who end up happy are the ones who make the most of whatever happens.",
 "What's something that didn't go your way, that you could still make the best of?"),
("If you don't have time to do it right, when will you have time to do it over?",
 "John Wooden", ["basketball"],
 "Rushing homework or a drill means you'll probably have to do it again. It's faster to do it right the first time.",
 "What's something you usually rush that deserves more care?"),
("It's not whether you get knocked down; it's whether you get up.",
 "Vince Lombardi", ["football"],
 "In football everyone gets knocked down, it's part of the game. Lombardi, who the Super Bowl trophy is named after, says what counts is getting back up.",
 "What knocked you down recently, and how did you get back up?"),
("It ain't over till it's over.",
 "Yogi Berra", ["baseball"],
 "Yogi Berra was a great catcher famous for funny sayings. This one sounds silly, but it's true: never give up on a game until it's actually finished.",
 "What game did you almost give up on, that turned out okay?"),
("Baseball is ninety percent mental. The other half is physical.",
 "Yogi Berra", ["baseball"],
 "The math is wrong on purpose (90 plus a half is more than 100!). That's the joke. But he's right that sports happen in your head as much as in your body.",
 "How does your mood change how you play?"),
("There may be people that have more talent than you, but there's no excuse for anyone to work harder than you do.",
 "Derek Jeter", ["baseball"],
 "You can't choose how talented you are. You can choose how hard you work. Jeter says nobody should out-work you.",
 "Where could you give a little more effort today?"),
("My motto was always to keep swinging. Whether I was in a slump or feeling badly or having trouble off the field, the only thing to do was keep swinging.",
 "Hank Aaron", ["baseball"],
 "A slump is when nothing is working. Hank Aaron broke Babe Ruth's home run record by always taking the next swing, even on bad days.",
 "What's something you'll keep \"swinging\" at, even if it's not going well?"),
("Any time you have an opportunity to make a difference in this world and you don't, then you are wasting your time on Earth.",
 "Roberto Clemente", ["baseball"],
 "Roberto Clemente was a baseball star who spent a lot of his time helping people who needed it. He believed helping others is one of the most important things you can do.",
 "What's one way you could help someone this week?"),
("The most important thing is to try and inspire people so that they can be great in whatever they want to do.",
 "Kobe Bryant", ["basketball"],
 "Kobe won five championships, but he said the best thing a great player can do is help other people be great too.",
 "Who inspires you? Who might you inspire?"),
("Pressure is a privilege.",
 "Billie Jean King", ["more"],
 "When you feel nervous before a big moment, it means you've earned a chance that matters. Billie Jean King, a tennis legend, says pressure is something lucky people get to feel.",
 "When have you felt nervous because something mattered?"),
("Start where you are. Use what you have. Do what you can.",
 "Arthur Ashe", ["more"],
 "You don't need the best gear or a perfect plan to start. Just begin with what you've got. Arthur Ashe was the first Black man to win Wimbledon.",
 "What could you start today, with what you already have?"),
("Never underestimate the power of dreams and the influence of the human spirit.",
 "Wilma Rudolph", ["more"],
 "Doctors thought Wilma Rudolph might never walk normally. She won three Olympic gold medals. She knows how powerful a dream can be.",
 "What's a dream you have that other people might think is too big?"),
("You can't put a limit on anything. The more you dream, the farther you get.",
 "Michael Phelps", ["more"],
 "Phelps won 23 Olympic gold medals, more than anyone. He's saying don't decide ahead of time how far you can go.",
 "If there were no limits, what would you try?"),
("Hard work has made it easy. That is my secret. That is why I win.",
 "Nadia Comăneci", ["more"],
 "Nadia Comăneci scored the first perfect 10 in Olympic gymnastics. Her moves looked easy because she'd practiced them thousands of times.",
 "What's something that got easy because you practiced it?"),
("Hard work beats talent when talent doesn't work hard.",
 "Tim Notke", ["more"],
 "Tim Notke was a high-school basketball coach. His line got famous because it's true: if you work harder than someone more talented, you can beat them.",
 "Where can hard work help you beat someone today?"),
("Here's how I'm going to beat you. I'm going to outwork you. That's it. That's all there is to it.",
 "Pat Summitt", ["basketball"],
 "Pat Summitt won more games than almost any college basketball coach. Her secret wasn't a trick. It was working harder than everyone else.",
 "Who's someone you could out-work this week?"),
("Today I consider myself the luckiest man on the face of the earth.",
 "Lou Gehrig", ["baseball"],
 "Lou Gehrig said this when he was very sick and had to stop playing. Even then, he thought about all the good things in his life: his team, his fans, his family. Being thankful is a choice.",
 "What are three things you're lucky to have?"),
("The day you think there is no improvements to be made is a sad one for any player.",
 "Lionel Messi", ["soccer"],
 "Even Messi, one of the best ever, always looks for ways to get better. The day you think you know it all, you stop improving.",
 "What's one thing you could still get better at, even if you're already good at it?"),
("I trained four years to run nine seconds.",
 "Usain Bolt", ["more"],
 "A 100-meter race takes less than 10 seconds. Bolt trained for years for those few seconds. Big moments are short, but getting ready for them takes a long time.",
 "What are you practicing now that might pay off later?"),
]
